namespace: microserviceC

public:
  - web:3000

services:
  web:
    image: node:4
    volumes:
      - .:/microserviceC
    working_dir: /microserviceC
    environment:
      - "MICROSERVICED_ENDPOINT=http://microserviceD"
    command: [npm, start]

dependencies:
  - microserviceD

setup:
  - npm install
