namespace: microserviceC

public:
  - web

services:
  web:
    image: node:4
    ports:
      - "3000:3000"
    volumes:
      - .:/microserviceC
    working_dir: /microserviceC
    environment:
      - "MICROSERVICED_ENDPOINT=http://microserviceD"
    command: [npm, start]

dependencies:
  - microserviceD

setup:
  - npm install
